### PR TITLE
Transform to python3

### PR DESCRIPTION
**Pull request by simonre**
Hi, 
the code so far cannot be run in python3 so I made it work with python3.

### CODE REVIEW

**Comment by ajithvcoder** [comment]
@dangweili  could you please merge this python2 is almost deprecated

**Comment by ajithvcoder** [comment]
@simonre have u tested it  ? is it working perfectly for all datasets ?

**Comment by simonre** [comment]
No, I haven't done any extensive testing. I needed the Peta dataset to work and thought maybe I can spare some other people the work :smile:

**Comment by ajithvcoder** [comment]
@simonre  this doesnt work on rap2 dataset i think its because of batch size not sure or the colabs gpu . but i got another repo https://github.com/valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition and this is working with all datasets if u want u can use

**Pull request closed without merging**
